/**
 * datastore.js — static data layer for Vercel deployment (no Flask backend).
 *
 * snapshot.json    — 6 demo business dashboards generated by data/export_snapshot.py
 * portfolio-summary.json — 507 business records (bundled, used for Portfolio page)
 * /data/portfolio/*.json — per-business detail files served from public/ (on-demand fetch)
 *
 * DBR and business-profiler calculations are replicated from models/dbr_model.py
 * and models/business_classifier.py + models/expense_estimator.py.
 */

import snapshot       from "../data/snapshot.json";
import portfolioData  from "../data/portfolio-summary.json";

// Wrap plain data in a Promise shaped like an axios response: { data: ... }
const res = (data) => Promise.resolve({ data });

// ── Track 1: existing businesses ─────────────────────────────────────────────

export const getDashboard = (id) => {
  const d = snapshot[id];
  if (!d) return Promise.reject(new Error(`No static snapshot for "${id}"`));
  return res(d);
};

export const getForecast = (id) => {
  const d = snapshot[id];
  if (!d) return Promise.reject(new Error(`No static snapshot for "${id}"`));
  return res({
    business_id:    id,
    summary:        d.forecast?.summary,
    series:         d.forecast?.series || [],
    dynamic_credit: d.dscr?.dynamic_credit_limit,
  });
};

// ── Portfolio ─────────────────────────────────────────────────────────────────

export const getPortfolioSummary = () => res(portfolioData);

export const getPortfolioStats = () => {
  const data  = portfolioData;
  const total = data.length;

  const riskCounts  = {};
  const fraudCounts = {};
  const archCounts  = {};
  const trendCounts = {};
  let smeReady = 0, dscrSum = 0, revSum = 0;

  for (const r of data) {
    riskCounts[r.risk_tier]     = (riskCounts[r.risk_tier]     || 0) + 1;
    fraudCounts[r.fraud_status] = (fraudCounts[r.fraud_status] || 0) + 1;
    archCounts[r.archetype_key] = (archCounts[r.archetype_key] || 0) + 1;
    trendCounts[r.revenue_trend]= (trendCounts[r.revenue_trend]|| 0) + 1;
    if (r.sme_transition_ready) smeReady++;
    dscrSum += r.dscr_score          || 0;
    revSum  += r.avg_daily_revenue_sar || 0;
  }

  return res({
    total_businesses:                   total,
    sme_transition_ready:               smeReady,
    avg_dscr_score:                     Math.round(dscrSum / total * 10000) / 10000,
    avg_daily_revenue_sar:              Math.round(revSum  / total * 100) / 100,
    total_portfolio_annual_revenue_sar: Math.round(revSum * 365),
    risk_tier_distribution:             riskCounts,
    fraud_status_distribution:          fraudCounts,
    archetype_distribution:             archCounts,
    revenue_trend_distribution:         trendCounts,
  });
};

// Portfolio business detail — fetched on demand from /public/data/portfolio/
export const getPortfolioBusiness = (bid) =>
  fetch(`/data/portfolio/${bid}_detail.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`${bid} not found (${r.status})`);
      return r.json();
    })
    .then((data) => ({ data }));

// ── Track 2: DBR calculator — replicates models/dbr_model.py (simple mode) ──

export const assessDBR = ({ monthly_salary, existing_obligations, requested_loan, loan_term_months }) => {
  const monthlyPayment  = Math.round((requested_loan / loan_term_months) * 100) / 100;
  const totalOblig      = Math.round((existing_obligations + monthlyPayment) * 100) / 100;
  const dbrRatio        = Math.round((totalOblig / monthly_salary) * 10000) / 10000;
  const approved        = dbrRatio <= 0.33;

  const maxAllowedPmt   = monthly_salary * 0.33 - existing_obligations;
  const maxEligibleLoan = !approved && maxAllowedPmt > 0
    ? Math.round(maxAllowedPmt * loan_term_months * 100) / 100 : 0;

  const riskTier =
    dbrRatio <= 0.15 ? "very_low"      :
    dbrRatio <= 0.25 ? "low"           :
    dbrRatio <= 0.33 ? "medium"        : "exceeds_limit";

  const reason = approved
    ? `DBR of ${(dbrRatio * 100).toFixed(1)}% is within the SAMA 33% cap. Loan of SAR ${Math.round(requested_loan).toLocaleString()} approved.`
    : `DBR of ${(dbrRatio * 100).toFixed(1)}% exceeds SAMA 33% cap. Maximum eligible loan: SAR ${maxEligibleLoan.toLocaleString()}.`;

  return res({
    monthly_salary_sar:            monthly_salary,
    existing_obligations_sar:      existing_obligations,
    requested_loan_sar:            requested_loan,
    loan_term_months,
    monthly_payment:               monthlyPayment,
    total_monthly_obligations:     totalOblig,
    dbr_ratio:                     dbrRatio,
    dbr_limit:                     0.33,
    dbr_status:                    approved ? "within_limit" : "exceeds_limit",
    risk_tier:                     riskTier,
    approved,
    max_eligible_loan_sar:         approved ? null : maxEligibleLoan,
    salary_deduction_agreement:    approved,
    reason,
  });
};

// ── Track 2: Business profiler — replicates classifier + expense estimator ───
//
// Ticket size and velocity tags drive COGS/labor lookups from
// models/expense_estimator.py. Archetype mapping mirrors
// models/business_classifier.py cluster descriptions.

const COGS_BY_TICKET = {
  very_low: 0.55, low: 0.45, mid: 0.30, high: 0.15, very_high: 0.08,
};
const COGS_INVENTORY = {
  very_high: 0.65, high: 0.65, mid: 0.58,
};
const LABOR_BY_VELOCITY = {
  very_high: 0.16, high: 0.14, moderate: 0.10, low: 0.06, very_low: 0.03,
};
const ARCHETYPE_MAP = {
  "very_low-very_high":  "high_freq_low_ticket_food",
  "very_low-high":       "high_freq_low_ticket_food",
  "very_low-moderate":   "low_ticket_steady_essential",
  "low-very_high":       "high_freq_mid_ticket_retail",
  "low-high":            "high_freq_mid_ticket_retail",
  "low-moderate":        "mid_ticket_mid_freq_services",
  "mid-moderate":        "mid_ticket_mid_freq_services",
  "mid-low":             "mid_ticket_mid_freq_services",
  "mid-very_low":        "low_freq_mid_ticket_dealer",
  "high-low":            "low_freq_high_ticket_automotive",
  "high-very_low":       "sparse_high_ticket_brokerage",
  "very_high-very_low":  "sparse_high_ticket_brokerage",
  "very_high-low":       "sparse_high_ticket_brokerage",
};

export const getBusinessProfile = ({
  typical_ticket_sar       = 50,
  expected_daily_customers = 20,
  is_consumer_facing       = true,
  sells_high_value_items   = false,
  expected_payment_mix     = "mixed",
  holds_physical_inventory = false,
} = {}) => {
  const ticketSize =
    typical_ticket_sar < 50    ? "very_low"  :
    typical_ticket_sar < 500   ? "low"       :
    typical_ticket_sar < 5000  ? "mid"       :
    typical_ticket_sar < 50000 ? "high"      : "very_high";

  const velocityTag =
    expected_daily_customers >= 150 ? "very_high" :
    expected_daily_customers >= 60  ? "high"      :
    expected_daily_customers >= 20  ? "moderate"  :
    expected_daily_customers >= 5   ? "low"       : "very_low";

  let cogs = COGS_BY_TICKET[ticketSize];
  if (holds_physical_inventory) {
    cogs = COGS_INVENTORY[ticketSize] ?? 0.52;
  }

  let labor = LABOR_BY_VELOCITY[velocityTag];
  if (expected_payment_mix === "mostly_cash") labor += 0.03;

  const total     = Math.min(0.92, Math.max(0.25, cogs + labor + 0.08 + 0.008));
  const netMargin = Math.round((1 - total) * 10000) / 10000;

  const archetypeKey = `${ticketSize}-${velocityTag}`;
  const archetypeDescription = ARCHETYPE_MAP[archetypeKey] || "mid_ticket_mid_freq_services";

  const riskIndication = netMargin > 0.35 ? "low" : netMargin > 0.20 ? "medium" : "high";

  const confidence = Math.min(0.65,
    0.45 + (sells_high_value_items ? 0.05 : 0) + (is_consumer_facing ? 0.03 : 0));

  return res({
    cluster_id:           0,
    archetype_description: archetypeDescription,
    confidence:           Math.round(confidence * 10000) / 10000,
    refinement_status:    "predicted",
    behavioral_profile:   { ticket_size: ticketSize, transaction_velocity: velocityTag },
    expense_estimate: {
      total_expense_ratio: Math.round(total * 10000) / 10000,
      breakdown: {
        cogs_ratio:     Math.round(cogs  * 10000) / 10000,
        labor_ratio:    Math.round(labor * 10000) / 10000,
        overhead_ratio: 0.08,
        stability_adj:  0.008,
      },
      net_margin_estimate: netMargin,
      holds_inventory:     holds_physical_inventory,
    },
    preliminary_credit_profile: {
      risk_indication: riskIndication,
      note: "Based on intake form only. Connect POS data for full assessment.",
    },
  });
};
